"""added password field

Revision ID: 220869e63e48
Revises: 3de3dc37882f
Create Date: 2021-09-10 22:59:23.312906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '220869e63e48'
down_revision = '3de3dc37882f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
